### ISSUE TITLE
Username button does nothing when clicked on other pages

### ISSUE THREAD

**Issue by hellobordois** [Nudes-Token/feedback#20]
Username button does nothing when clicked on pages that aren't the Memes page.

<img width="1299" alt="Screen Shot 2022-06-14 at 9 17 49 PM" src="https://user-images.githubusercontent.com/107487385/173715953-722f9c16-e565-4828-9e6d-8a17f85dd499.png">

**Comment by adrian-fjellberg** [comment]
@Topstar-web Do you know what causes this issue? Maybe the modal is missing on the other pages. Can you see if you can fix this issue?

**Comment by odd86** [comment]
This should take you to the profile page on v2.1
Maybe now it should just show you the signout modal?

**Comment by odd86** [comment]
Fixed. Will go to profile page when we have that

**Comment by adrian-fjellberg** [comment]
Not fixed if not logged in when not on the feed page.

How to reproduce:
1. Navigate to https://development.nudes-army-webpage.pages.dev/get-started directly or refresh when on page.
2. The page will not log you back in (separate issue maybe?)
3. When you click the button, nothing happens.

Expected behavior:
- I expect the website to be able to log me back in even if I am not on the feed page.
- I expect to see a login or logout modal when I click the button (depending on my current login-state)
