### ISSUE TITLE
OG NFT discount fee not calculated right

### ISSUE THREAD

**Issue by Geralt-of-R1via** [Nudes-Token/feedback#3]
OG NFT discount fee is showing 75% discount for 2 OG's

Minting pop up screen is showing different discount, 57% 

![222222](https://user-images.githubusercontent.com/107487414/173605708-2ca41906-e181-4529-a453-063f9c9c945f.JPG)

![111111](https://user-images.githubusercontent.com/107487414/173605808-5e9f03fb-a505-49bf-bcb9-409ac199e82d.JPG)

**Comment by adrian-fjellberg** [comment]
@Topstar-web Could you take a look at this?

I think 75% is the one that is correct. Take a look at this message:
https://discord.com/channels/905377023072043018/960511730344153098/985980743169769542

**Comment by Geralt-of-R1via** [comment]
Nothing happens when I open a link. Only discord with a blank page

**Comment by Geralt-of-R1via** [comment]
According to Mr.Google msg's 2 OG's should provide 75% discount fee

**Comment by adrian-fjellberg** [comment]
> According to Mr.Google msg's 2 OG's should provide 75% discount fee

Thanks for clarifying @Geralt-of-R1via

**Comment by Topstar-web** [comment]
@adrian-fjellberg 
Fixed this issue and made a PR for this
https://github.com/Nudes-Token/nudes-army-webpage/pull/21

**Comment by adrian-fjellberg** [comment]
@Topstar-web Closed this issue and the pull request as @odd86 said this was already fixed.

**Comment by Geralt-of-R1via** [comment]
I'm still seeing same ratio like before. It should be 75% but I'm getting 57%

**Comment by adrian-fjellberg** [comment]
> I'm still seeing same ratio like before. It should be 75% but I'm getting 57%

@Geralt-of-R1via Is this still an issue?

**Comment by Geralt-of-R1via** [comment]
> > I'm still seeing same ratio like before. It should be 75% but I'm getting 57%
> 
> @Geralt-of-R1via Is this still an issue?

 Yes, nothing changed for me.  Getting 57% discount and counter on top is showing it should be 75% 

![1111](https://user-images.githubusercontent.com/107487414/186419964-b35bd9be-7e3d-4c07-921a-a2827f27a139.JPG)
